apiVersion: v1
kind: Service
metadata:
  name: json-schema
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: json-schema
  ports:
  - name: "80"
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-schema
spec:
  selector:
    matchLabels:
      app: json-schema
  template:
    metadata:
      labels:
        app: json-schema
    spec:
      containers:
      - name: json-schema
        image: fintlabs.azurecr.io/json-schema:build.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
